### ISSUE TITLE
The difference between LiveCharts and LiveCharts2

### ISSUE THREAD

**Issue by ghost1372** [Live-Charts/LiveCharts2#1]
Hi, I am very happy that this project has resumed.
If possible, please explain about the features of version 2 and its roadmap.
Will it be free? I hope this version also uses the MIT license.
thank you.

**Comment by beto-rodriguez** [comment]
Hi!

I forgot to add the license file, yes it is under the MIT license, just added it.
Yes it will be free, and will also have a paid version to try to keep the project alive.

The main difference is that we can take v2 to Xamarin, UNO platform, Avalonia, maybe WASM, and of course WPF, WinForms, UWP, to achieve this in v0 was practically impossible.

I also added a readme.md to the project, take a look at the main page of the repo.

https://github.com/Live-Charts/LiveCharts2

**Comment by ghost1372** [comment]
Thank you @beto-rodriguez 
When can we use nuget packages? Does it take too long?

**Comment by beto-rodriguez** [comment]
I hope we can have a Nuget package in about 1 or 2 months

**Comment by jamsoft** [comment]
I can only applaud you for picking this up again. Really great library.

Alas, I'm stuck on 4.8 for now as the upgrade to my massive WPF app is a rewrite really too. I appreciate how much work that is. Thank you!

**Comment by tarekfb** [comment]
> I hope we can have a Nuget package in about 1 or 2 months

Any progress on the package? Thanks

**Comment by ghost1372** [comment]
> > I hope we can have a Nuget package in about 1 or 2 months
> 
> Any progress on the package? Thanks

yes nuget is available
https://github.com/beto-rodriguez/LiveCharts2/issues/35#issuecomment-842824341

**Comment by LaPeste** [comment]
Sorry for dropping by in a closed issue, but since there is also a discussion about this. Do you have plans to support UNO too?

**Comment by beto-rodriguez** [comment]
@LaPeste Uno uses UWP or WinUI, LiveCharts already provides both views, you can create a Uno app (UWP) and use the LiveCharts.SkiaSharpView.UWP package.

For the newer version of Uno, there is a step missing as far as I am aware of, https://github.com/mono/SkiaSharp/issues/1787

**Comment by LaPeste** [comment]
First thing I did was to download exactly the one you said, but I got an error like "platform not supported" or something along those lines. I can dig it if you need it.
But in fairness I'm using Uno `4.1.0-dev.40`, which I believe it's what you're referring to as "the newer version of Uno".

Thank you for taking the time to answer.

**Comment by LaPeste** [comment]
I'm also trying to do this from MacOs, this could be a problem. Am I right?
